workspace: /NHNHOME/WORKSPACE/26msit001_A/bispl_lab/youngmin/bench_ws/oxford
datasets:
  - oxford
methods:
  - base_ra16_k1
evaluation:
  traj: {enable: true, vis: false}
  auc: {enable: true, vis: false, aggregation: both}
  depth: {enable: false}
  points: {enable: false}
