dataset: neural_rgbd
raw_data_root: /NHNHOME/WORKSPACE/26msit001_A/bispl_lab/youngmin/data_bench/neural_rgbd_data
sampling:
  strategy: sequence
  stride: 5
evaluation:
  depth:
    gt_clip:
      min: 0.0
      max: 10.0
