dataset: oxford_spires
raw_data_root: /NHNHOME/WORKSPACE/26msit001_A/bispl_lab/seonghyun/R3R/data/oxford_spires
sampling:
  strategy: sequence
  stride: 12
evaluation:
  depth:
    gt_clip:
      min: 0.0
      max: 200.0
  points:
    icp_threshold: 0.5
